### ISSUE TITLE
urls.py missing? 

### ISSUE THREAD

**Issue by JJZolper** [GetStream/django_twitter#10]
Shouldn't there be a urls.py under stream_twitter? Also I feel some other files conceptually would be missing as well like a wsgi.py etc. Just thought I'd point it out. I'm following the example and when I was looking for what you had for the urls for follow and unfollow I didn't seem to find them.

**Comment by tbarbugli** [comment]
url module is here https://github.com/GetStream/django_twitter/blob/master/pytutorial/urls.py
