### ISSUE TITLE
confusion about feed groups

### ISSUE THREAD

**Issue by scotthou94** [GetStream/django_twitter#13]
say user_a is following user_b, when I load the timeline feed like this:
```python
 feeds = feed_manager.get_feed('timeline', user_a.id)
```
all I got is user_b's tweet
but when I load the user feed like this
```python
feeds = feed_manager.get_feed('user', user_a.id)
```
all I got is user_a's tweet.
But obviously I need both user_a and user_b's tweet to display in user_a's timeline.
here's my getstream settings:
```python
STREAM_API_KEY = 'key'
STREAM_API_SECRET = 'secret'
STREAM_NEWS_FEEDS = dict(timeline='timeline')
```
is there a way to fix this? thanks in advance

**Comment by tbarbugli** [comment]
Not all applications have this use case. The simplest way to get what you need is to create a follow relationship between `user_a`'s timeline and `user_a`'s user feed. Perhaps it's something you can do when the user is created using Django's signals.
