### ISSUE TITLE
error deploying to heroku

### ISSUE THREAD

**Issue by wondersoftheworld** [GetStream/django_twitter#14]
Postdeploy exit code was not 0

heroku build log: 

[36;1mOperations to perform:[0m
[1m  Apply all migrations: [0mstream_twitter, admin, sessions, auth, sites, socialaccount, contenttypes, account
[36;1mRunning migrations:[0m
  Rendering model states...[32;1m DONE[0m
  Applying contenttypes.0001_initial...[32;1m OK[0m
  Applying auth.0001_initial...[32;1m OK[0m
  Applying account.0001_initial...[32;1m OK[0m
  Applying account.0002_email_max_length...[32;1m OK[0m
  Applying admin.0001_initial...[32;1m OK[0m
  Applying admin.0002_logentry_remove_auto_add...[32;1m OK[0m
  Applying contenttypes.0002_remove_content_type_name...[32;1m OK[0m
  Applying auth.0002_alter_permission_name_max_length...[32;1m OK[0m
  Applying auth.0003_alter_user_email_max_length...[32;1m OK[0m
  Applying auth.0004_alter_user_username_opts...[32;1m OK[0m
  Applying auth.0005_alter_user_last_login_null...[32;1m OK[0m
  Applying auth.0006_require_contenttypes_0002...[32;1m OK[0m
  Applying auth.0007_alter_validators_add_error_messages...[32;1m OK[0m
  Applying sessions.0001_initial...[32;1m OK[0m
  Applying sites.0001_initial...[32;1m OK[0m
  Applying sites.0002_alter_domain_unique...[32;1m OK[0m
  Applying socialaccount.0001_initial...[32;1m OK[0m
  Applying socialaccount.0002_token_max_lengths...[32;1m OK[0m
  Applying socialaccount.0003_extra_data_default_dict...[32;1m OK[0m
  Applying stream_twitter.0001_initial...[32;1m OK[0m
Installed 116 object(s) from 1 fixture(s)
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/app/pytutorial/management/commands/after_deploy.py", line 17, in handle
    tweet.delete()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/base.py", line 862, in delete
    return collector.delete()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/models/deletion.py", line 316, in delete
    sender=model, instance=obj, using=self.using
  File "/app/.heroku/python/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 192, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/app/.heroku/python/lib/python2.7/site-packages/stream_django/managers.py", line 77, in activity_delete
    result = feed.remove_activity(foreign_id=instance.activity_foreign_id)
  File "/app/.heroku/python/lib/python2.7/site-packages/stream/feed.py", line 106, in remove_activity
    url, signature=token, params=params)
  File "/app/.heroku/python/lib/python2.7/site-packages/stream/client.py", line 225, in delete
    return self._make_request(self.session.delete, *args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/stream/client.py", line 170, in _make_request
    return self._parse_response(response)
  File "/app/.heroku/python/lib/python2.7/site-packages/stream/client.py", line 115, in _parse_response
    self.raise_exception(parsed_result, status_code=response.status_code)
  File "/app/.heroku/python/lib/python2.7/site-packages/stream/client.py", line 207, in raise_exception
    raise exception
stream.exceptions.ApiKeyException: api_key is invalid

**Comment by JelteF** [comment]
This should be fixed now by https://github.com/GetStream/django_twitter/commit/63f78d2257f3c807de66a3118cc0ba23198df745

Please reopen if it is still broken.

**Comment by wondersoftheworld** [comment]
Build succeeded this time, about 40 minutes later, but url returns Server Error (500).

**Comment by tbarbugli** [comment]
@wondersoftheworld could you be more specific on how you get the error?

**Comment by wondersoftheworld** [comment]
Sure @tbarbugli.
I deployed on heroku. It took a very long time for the build to complete (about 40 minutes). Once deployment was completed,  when I checked the website (twito.herokuapp.com), I got the 500 server error. I hope this is clear.

**Comment by tbarbugli** [comment]
weird, can you append the output of heroku logs?

**Comment by wondersoftheworld** [comment]
-----> Python app detected
-----> Installing python-2.7.12
     $ pip install -r requirements.txt
       Collecting dj-database-url==0.3.0 (from -r requirements.txt (line 1))
         Downloading dj_database_url-0.3.0-py2.py3-none-any.whl
       Collecting Django==1.9 (from -r requirements.txt (line 2))
         Downloading Django-1.9-py2.py3-none-any.whl (6.6MB)
       Collecting gnureadline==6.3.3 (from -r requirements.txt (line 3))
         Downloading gnureadline-6.3.3.tar.gz (2.5MB)
       Collecting gunicorn==19.2.1 (from -r requirements.txt (line 4))
         Downloading gunicorn-19.2.1-py2.py3-none-any.whl (110kB)
       Collecting ipython==2.4.1 (from -r requirements.txt (line 5))
         Downloading ipython-2.4.1-py27-none-any.whl (2.8MB)
       Collecting Pillow==2.7.0 (from -r requirements.txt (line 6))
         Downloading Pillow-2.7.0.tar.gz (7.4MB)
       Collecting psycopg2==2.5.4 (from -r requirements.txt (line 7))
         Downloading psycopg2-2.5.4.tar.gz (682kB)
       Collecting pytz==2014.10 (from -r requirements.txt (line 8))
         Downloading pytz-2014.10-py2.py3-none-any.whl (477kB)
       Collecting requests==2.5.1 (from -r requirements.txt (line 9))
         Downloading requests-2.5.1-py2.py3-none-any.whl (464kB)
       Collecting six==1.9.0 (from -r requirements.txt (line 10))
         Downloading six-1.9.0-py2.py3-none-any.whl
       Collecting stream-django==1.3.1 (from -r requirements.txt (line 11))
         Downloading stream-django-1.3.1.tar.gz
       Collecting stream-python==2.3.8 (from -r requirements.txt (line 12))
         Downloading stream-python-2.3.8.tar.gz
       Collecting whitenoise==1.0.6 (from -r requirements.txt (line 13))
         Downloading whitenoise-1.0.6-py2.py3-none-any.whl
       Collecting autopep8 (from -r requirements.txt (line 14))
         Downloading autopep8-1.2.4-py2.py3-none-any.whl (41kB)
       Collecting django-allauth==0.25.2 (from -r requirements.txt (line 15))
         Downloading django-allauth-0.25.2.tar.gz (408kB)
       Collecting rollbar (from -r requirements.txt (line 16))
         Downloading rollbar-0.13.6.tar.gz (46kB)
       Collecting pyjwt==1.3.0 (from stream-python==2.3.8->-r requirements.txt (line 12))
         Downloading PyJWT-1.3.0-py2.py3-none-any.whl
       Collecting httpsig==1.1.2 (from stream-python==2.3.8->-r requirements.txt (line 12))
         Downloading httpsig-1.1.2-py2.py3-none-any.whl
       Collecting pep8>=1.5.7 (from autopep8->-r requirements.txt (line 14))
         Downloading pep8-1.7.0-py2.py3-none-any.whl (41kB)
       Collecting python-openid>=2.2.5 (from django-allauth==0.25.2->-r requirements.txt (line 15))
         Downloading python-openid-2.2.5.tar.gz (301kB)
       Collecting requests-oauthlib>=0.3.0 (from django-allauth==0.25.2->-r requirements.txt (line 15))
         Downloading requests_oauthlib-0.7.0-py2.py3-none-any.whl
       Collecting pycrypto (from httpsig==1.1.2->stream-python==2.3.8->-r requirements.txt (line 12))
         Downloading pycrypto-2.6.1.tar.gz (446kB)
       Collecting oauthlib>=0.6.2 (from requests-oauthlib>=0.3.0->django-allauth==0.25.2->-r requirements.txt (line 15))
         Downloading oauthlib-2.0.0.tar.gz (122kB)
       Installing collected packages: dj-database-url, Django, gnureadline, gunicorn, ipython, Pillow, psycopg2, pytz, requests, six, pyjwt, pycrypto, httpsig, stream-python, stream-django, whitenoise, pep8, autopep8, python-openid, oauthlib, requests-oauthlib, django-allauth, rollbar
         Running setup.py install for gnureadline: started
           Running setup.py install for gnureadline: finished with status 'done'
         Running setup.py install for Pillow: started
           Running setup.py install for Pillow: finished with status 'done'
         Running setup.py install for psycopg2: started
           Running setup.py install for psycopg2: finished with status 'done'
         Running setup.py install for pycrypto: started
           Running setup.py install for pycrypto: finished with status 'done'
         Running setup.py install for stream-python: started
           Running setup.py install for stream-python: finished with status 'done'
         Running setup.py install for stream-django: started
           Running setup.py install for stream-django: finished with status 'done'
         Running setup.py install for python-openid: started
           Running setup.py install for python-openid: finished with status 'done'
         Running setup.py install for oauthlib: started
           Running setup.py install for oauthlib: finished with status 'done'
         Running setup.py install for django-allauth: started
           Running setup.py install for django-allauth: finished with status 'done'
         Running setup.py install for rollbar: started
           Running setup.py install for rollbar: finished with status 'done'
       Successfully installed Django-1.9 Pillow-2.7.0 autopep8-1.2.4 dj-database-url-0.3.0 django-allauth-0.25.2 gnureadline-6.3.3 gunicorn-19.2.1 httpsig-1.1.2 ipython-2.4.1 oauthlib-2.0.0 pep8-1.7.0 psycopg2-2.5.4 pycrypto-2.6.1 pyjwt-1.3.0 python-openid-2.2.5 pytz-2014.10 requests-2.5.1 requests-oauthlib-0.7.0 rollbar-0.13.6 six-1.9.0 stream-django-1.3.1 stream-python-2.3.8 whitenoise-1.0.6
     $ python manage.py collectstatic --noinput
       73 static files copied to '/app/static', 73 post-processed.
-----> Discovering process types
       Procfile declares types -> web
-----> Compressing...
       Done: 52.8M
-----> Launching...
       Released v5
       https://twito.herokuapp.com/ deployed to Heroku

**Comment by JelteF** [comment]
Hmmm, the output seems fine. Could you try deploying a new one and see if that has the same problem. When I deploy one it just work, it also takes only +-2 minutes to deploy for me.

If that still doesn't help can you send some of the logs of the app?

**Comment by wondersoftheworld** [comment]
Sure let me give it another shot. Thanks for your prompt responses.
