### ISSUE TITLE
Heroku deploy returning Server Error (500)

### ISSUE THREAD

**Issue by wondersoftheworld** [GetStream/django_twitter#18]
Build succeeded this time about 40 minutes later, but url returns Server Error (500).

**Comment by tbarbugli** [comment]
Try enabling debug mode:

```
heroku config:set DEBUG=on
heroku restart
```

**Comment by tbarbugli** [comment]
and add a link to the app if possible

**Comment by wondersoftheworld** [comment]
works now. thanks

**Comment by tbarbugli** [comment]
remember to switch debug mode off and restart the app ;)
