### ISSUE TITLE
Github signup results in error

### ISSUE THREAD

**Issue by ralphite** [GetStream/django_twitter#21]
I tried to signup with Github in the demo environment and got the following error:

IntegrityError at /accounts/github/login/callback/
null value in column "last_login" violates not-null constraint
DETAIL:  Failing row contains (1212, !P4aTcHecsphMmQemYg3Rm9jPofp73YjOjh0XZV7A, null, f, ralphite, Yadong, Wen, , f, t, 2017-09-26 08:12:53.196923+00).

**Comment by dwightgunning** [comment]
I've just replicated this. Looking into a solution.

**Comment by dwightgunning** [comment]
Located a database migration issue. Applied a fix and looks resolved to me.

@ralphite feel free to try again and let us know if this has resolved the issue for you. Thanks again for the report!

I'll close off in 14 days if we're not hearing back.
