### ISSUE TITLE
http://tw.getstream.io/timeline/ FeedConfigException at /timeline/

### ISSUE THREAD

**Issue by murdav** [GetStream/django_twitter#26]
Dear All,

Checking http://tw.getstream.io/timeline/ I get FeedConfigException at /timeline/.
Thanks.

D

**Comment by dwightgunning** [comment]
Thanks for the report! This must have arisen after we did some maintenance on our demo apps a few weeks back. I've just fixed the major error; we'll be re-running some data pre-population scripts shortly to provide some more interesting initial data after you signup and follow some accounts.
