### ISSUE TITLE
Getting server error 500 on heroku

### ISSUE THREAD

**Issue by Ndidi** [GetStream/django_twitter#28]
I turned debug mode on and get a `relation "auth_user" does not exist`.

Here's a link to the project: https://django-ndidi-twitter.herokuapp.com/

The only alteration is adding `dj-database-url==0.5.0` to the end of `requirements.txt`

**Comment by tbarbugli** [comment]
sounds like the database is not initialized correctly (Django migrations did not run). How did you setup this?

**Comment by Ndidi** [comment]
The 'Deploy to Heroku' button on the project page consistently failed (I don't have an example of the output).

- I created a new project on Heroku
- Added the Stream and Postgres add-ons to the project
- Cloned this repo
- Set Heroku as the remote via the CLI
- Added the `dj_database_url` module
- Then pushed

**Comment by tbarbugli** [comment]
I fixed it on master, one dependency was indeed missing. Thank you for letting us know!
