### ISSUE TITLE
  ERROR: Failed building wheel for Pillow

### ISSUE THREAD

**Issue by sucrecacao** [GetStream/django_twitter#31]
Failled to build pillow on a virtualenv.
Get a really long error message ending with:
`ERROR: Command errored out with exit status 1: venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3nw04j89/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3nw04j89/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d2gme0ys/install-record.txt --single-version-externally-managed --compile --install-headers venv/include/site/python3.7/Pillow Check the logs for full command output.
`

**Comment by sucrecacao** [comment]
Solved by making sure every Pillow external library are installed. See the list here https://pillow.readthedocs.io/en/latest/installation.html 
Then remplaced `Pillow==6.2.0` (latest version) in requirements.txt and it worked

**Comment by sucrecacao** [comment]
A better answer might to be sure you run on python3.6 and not python3.7

**Comment by romybompart** [comment]
Hi I'm running python 3.6.9, using pip version 20.1.1
The solution i found is writted here:  [https://github.com/scrapy/scrapy/issues/2115#issuecomment-231849637](https://github.com/scrapy/scrapy/issues/2115#issuecomment-231849637)

**Python 3, you'll need**

```
sudo apt-get install python3 python-dev python3-dev \
     build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev \
     python-pip
```

**Python 2, you'll need**

```
sudo apt-get install python-dev  \
     build-essential libssl-dev libffi-dev \
     libxml2-dev libxslt1-dev zlib1g-dev \
     python-pip
```

**Comment by HelloMukama** [comment]
I solved this by explicitly deleting the version numbering inside of the `requirements.txt` file
That way pip fetched the latest `pillow` version
so if forexample you had ...
`pillow==7.0.2`
change it to ..
`pillow`

then save the file and rerun the` pip install -r requirements.txt` line and it shd work

**Comment by DamiCode18** [comment]
thanks @hellomukama, that make sense, solved my problem

**Comment by benjaminmakowsky** [comment]
@hellomukama thanks, works now

**Comment by RamlalitY-HnH** [comment]
@HelloMukama thanks, worked

**Comment by InnoExcell** [comment]
Thanks @HelloMukama. It worked perfectly for me as well.

**Comment by David-hu123** [comment]
@HelloMukama works!

**Comment by Yuan-Tian2020** [comment]
> I solved this by explicitly deleting the version numbering inside of the `requirements.txt` file That way pip fetched the latest `pillow` version so if forexample you had ... `pillow==7.0.2` change it to .. `pillow`
> 
> then save the file and rerun the` pip install -r requirements.txt` line and it shd work

Im sorry to ask this, where can i find requirements.txt?

**Comment by AnkitaJaisw** [comment]
ERROR: Could not build wheels for Pillow, reportlab, which is required to install pyproject.toml-based projects

**Comment by JackObid** [comment]
> ERROR: Could not build wheels for Pillow, reportlab, which is required to install pyproject.toml-based projects

Try pip install --upgrade pip setuptools wheel
