### ISSUE TITLE
Todo: github signup post signal to follow self and all scientists

### ISSUE THREAD

**Issue by yoland68** [GetStream/django_twitter#9]

**Comment by tbarbugli** [comment]
can you change this to only auto follow a bunch of them? (perhaps some
pseudo random set of users)

**Comment by yoland68** [comment]
yeahhhh

**Comment by yoland68** [comment]
Exactly how I got annoyed by Twitter at the beginning :)

**Comment by dwightgunning** [comment]
Closing this off as there doesn't appear to be too much more that we can do here. Though I'm happy to discuss further and/or reopen as appropriate.
